use_frameworks!

target 'MGDeeplinkNavigator_Example' do
  pod 'MGDeeplinkNavigator/MGDeeplinkNavigator_Extension', :path => '../'

  target 'MGDeeplinkNavigator_Tests' do
    inherit! :search_paths

  pod 'Quick'
  pod 'Nimble'
  end
end
